apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: samba-pvc
  namespace: samba
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi

