---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: samba-credentials
  namespace: samba
spec:
  encryptedData:
    password: AgBweM9CR3gIBJin2OnPELiNI0t/m7qvIrlfLnX9JGhJEIpreeWsrJDIMpwUAetsiCAqnVAoKXvK+vVtfJquaS2UYAVo76gGBsRPdfL0APA3kosS2gO2xkBao8fCj8qj0qaADchwiTzMFQcr08H0T12jy1YWN2ZNpbvuUFuZ0TRidXodYFskJdPLD+1aS+sNrIol1To2JSoQxePmuyf2EGjlTmLy4iN0fbvDDnW4IYvl0jkpFKU+zEzWRt9XFmtR22DPIKeb3gSDlRPEsdPnw5inEcgynnOGMYJDYGVk91ugnbffyiEQ4eoxonoWPrv+8VOMn1VtXNyLv7fwIY36l56YiBMhkg3tB9V7JVnXgfIjnAmavm2fT3g6Xzuh7PEgMBiFp1ceolLMCnk1dndzA4ggnAPWJ6nu2xrAsrp/EXLraTf3wJFQMrAwB20OJ3F1NtOEeSLc1kqjf896VJnAQNnb5ZH//IxfPPb4VRJU3YoX5p8oIYXOW/RHmshA5IvieCLmuUGQz24KuCigbMRKkhBqE7habKDAuZxSMuuiRyeWDnus/xsAr/HO18co88i1OHqhkmu2KiORdO2GpYYCNTAIPTtfg7I/h0tP+m6riAI1d91NlW13L1vE7V2mvAWfoqoxl0vgVDWmenqtrS3z0H4m/Q3psi2xXmbLsiMU9UL47iONg0+cFDeax7P0OnjAe5EaDSQkyNOrNuQ=
    username: AgCLIJsV2R/Q68bupkT7p8cHGgVYnsx9WoEff84ezMjZXvap+wI7R9pN/F6fZZxhCAUZYgRwokJecZ6BFuGch7Fme1axIQZiESfwlXosnPPe83IvychUmkkPmp4pPqXVMDtGFRGtpRxu2PZ/BJWtn4H/Bu9YSgEc64KXHVB5Fwun/XHKapl/0EFVET43Bbk1XFEFYpjkBl8hDsDDUIoG8VMqG1A57+F5o5haFflzghVsLhFoGWKw7mVHYwQloAxR3gbAI5iv8Wfa1vWUjR8SjFpcQV5D1ORajiTuYS0xL6xPJTdUiR9mgOKSf/kk9gG6Oe3kIqumHo9pmfRoctJSXDp3AcDlsXwxkUBiZ6eXBHuCl6F6l6sZ6tugGhMOOjDqt+sA2l3VtHxv2m+SQaDU1+3T6zSNm76osqsFBbHhWvdP76kTIToKyXMZ4R/5naQZ7JO3/051fcWPp68VlF/QYtUkHeVzeKBWZuRUoHnMCDpDCMQKL5y+YbzManBix1lw7WwlaQBtfZ6eUzUX0mhBafCwqaHFx1A0rl4gA+hdCZTiwXl04sZGZrglR5TObYCbzfiEH4tlSJ/NFKz5REc9ZdH0gOf5YPTR2jdO34+fRiQX4JN21q1QQGPYfVFmBC7f64yb/T9ZLcwxdc3pFtybLcMK6V3WgrSrXRHAEXkH1w729T+ZiJtPG09TgvVP6ifvPiowA+GF0w==
  template:
    metadata:
      creationTimestamp: null
      name: samba-credentials
      namespace: samba
