crds:
  enabled: true

ingressShim:
  defaultIssuerKind: ClusterIssuer
  defaultIssuerName: selfsigned-cluster-issuer

# enable GatewayAPI support
config:
  apiVersion: controller.config.cert-manager.io/v1alpha1
  kind: ControllerConfiguration
  enableGatewayAPI: true