apiVersion: v1
kind: Service
metadata:
  labels:
    stack: librespeed
  name: librespeed
  namespace: librespeed
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    stack: librespeed
