---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: librespeed-password
  namespace: librespeed
spec:
  encryptedData:
    password: AgBhEsfirWbKOCIVYzJMhZDV8dpq1I0DjCV5bfgDv02K0W/9OX1ODMJTFMBil6d0lKelhlaWEreBEXkpwN2jR9hOA/XOxyZ/i8wEuPpezdI5kWdZNLPX157PBNW58IRxg70vhUoT671lojx9mpWVZqkDHA+fQS/fxeCVQ71NYtw0TKiDPRIrsbTsiMwSrSG5prnXgQLmGfu076M61e/0QFGaEDlobjS84gjGORcsQCtPl6kdV6KFr7hwWYbi159YmSWgpWFgtW6b/nagr3E2FqiXArR2KPIcIJyqpQI2moPXDqPWjZpSWwLTF+0/2mMeEnFPuizK8UL44Zu1lyL03mUHvWg8pYCiBf0GY5Lv36Te/Bnh3IRcctAmcolk2Hac22Uzzi7nNxvpH6cYU6/l1ZeFsLCplqrYngyqnMIxWn5G80VJpmdzKztblyz9W5WpsYtuwB+tR4GskS6wy8Su+Jc77HJaQMXxGcs/fytWQMQzEKQIUJOEa8Dr/5+5oOa8XjM38dZyzNXw5UQ2CCp8Qk7cXgjzRe38XAbTtxWsuBtVpTVGZ71dJprKPhKNcz+38oM/MaggfRofMIKmf2v/TBzwkxjT60vIKko5HobnW8NXAji4AO7OwL94wq4IDdfzTN2MqiG79DWmcBt7wBGutScP2m7jrr+FnaKDLIoZ0A+OpxmjTWr8Dz8KY7Q6I7crH6E0ufT0XKPfgQ==
  template:
    metadata:
      creationTimestamp: null
      labels:
        stack: password
      name: librespeed-password
      namespace: librespeed
    type: Opaque
