containerd_base: /mnt/nfs/cluster/bin/containerd
containerd_bins:
  - containerd
  - containerd-shim
  - containerd-shim-runc-v1
  - containerd-shim-runc-v2
  - containerd-stress
  - ctr

cni_base: /mnt/nfs/cluster/bin/cni-plugins
cni_bins:
  - bandwidth
  - bridge
  - dhcp
  - dummy
  - firewall
  - host-device
  - host-local
  - ipvlan
  - loopback
  - macvlan
  - portmap
  - ptp
  - sbr
  - static
  - tap
  - tuning
  - vlan
  - vrf

runc_base: /mnt/nfs/cluster/bin/runc
runc_bins:
  - runc

cri_base: /mnt/nfs/cluster/bin/kube
cri_bins:
  - crictl

kubelet_base: /mnt/nfs/cluster/bin/kube
kubelet_bins:
  - kubelet
  - kube-proxy
