services:
  nfs-server:
    container_name: nfs-server
    image: aabel011/nfs-server:latest
    environment:
      NFS_EXPORT_0: "/exports          *(rw,insecure,all_squash,anonuid=1001,anongid=1001,fsid=0,no_subtree_check)"
      NFS_EXPORT_1: "/exports/media    *(rw,insecure,all_squash,anonuid=1001,anongid=1001,no_subtree_check)"
      NFS_EXPORT_2: "/exports/pvs      *(rw,insecure,no_root_squash,sync,no_subtree_check)"
      NFS_VERSION: 4.2
    volumes:
      - /data/nfs/exports:/exports
      - /data/nfs/media:/exports/media
      - /data/nfs/pvs:/exports/pvs
      - /lib/modules:/lib/modules:ro
    cap_add:
      - 'SYS_ADMIN'
      - 'SYS_MODULE'
    network_mode: host
        #ports:
        #      - 111:111/tcp
        #      - 111:111/udp
        #      - 2049:2049/tcp
        #      - 2049:2049/udp
        #      - 32765:32765/tcp
        #      - 32765:32765/udp
        #      - 32766:32766/tcp
        #      - 32766:32766/udp
        #      - 32767:32767/tcp
        #      - 32767:32767/udp
    security_opt:
      #      - 'apparmor=nfs.apparmor'
      - 'apparmor=unconfined'
    restart: unless-stopped
    logging:
      options:
        max-size: 1m
        max-file: 3