---
version: "2.1"
services:
  librespeed:
    image: lscr.io/linuxserver/librespeed:latest
    container_name: librespeed
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=/run/secrets/password
      #- CUSTOM_RESULTS=false #optional
      #- DB_TYPE=sqlite #optional
      #- DB_NAME=DB_NAME #optional
      #- DB_HOSTNAME=DB_HOSTNAME #optional
      #- DB_USERNAME=DB_USERNAME #optional
      #- DB_PASSWORD=DB_PASSWORD #optional
      #- DB_PORT=DB_PORT #optional
      #    volumes:
      #      - /path/to/appdata/config:/config
    ports:
     - 80
    secrets:
      - password
    restart: unless-stopped
    labels:
      - traefik.http.routers.librespeed.rule=Host(`speed.home.lan`)
      - traefik.http.services.librespeed.loadbalancer.server.port=80
secrets:
  password:
    file: password.secret
