---

- name: For nfs clients, which should only be worker/non-control-plane nodes
  when: inventory_hostname in groups.workers
  block:
  - name: Copy readahead setter script
    copy:
      src: set-nfs-readahead.sh
      dest: /opt/set-nfs-readahead.sh
      mode: 0755

  - name: Run set-nfs-readahead every 10 minutes
    cron:
      name: set-nfs-readahead
      job: /opt/set-nfs-readahead.sh
      minute: "*/10"
      user: root  
  