version: "3"

services:
  traefik:
    container_name: traefik
    image: traefik:v2.4
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/traefik/traefik.toml:/traefik.toml
      - /data/traefik/traefik_dynamic.toml:/traefik_dynamic.toml
    restart: unless-stopped

