---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sealed-podsync-api-key
  namespace: downloaders
spec:
  encryptedData:
    PODSYNC_YOUTUBE_API_KEY: AgAe0YwKx8li9r6OvVq2+Gonpd7tiJWYB74Mb79KzN4JDGX0LyKCLGnnbRSgVAVrk1iH+hQathgWPfNVRnxH0ltUxxqKVpDyY5cJqR/VAWLcypq6boGAMPW2OOXL8tKpIb+PJZkhGN0Otyxl4N/ROREw6VX48id1anfcndbG96ghI3KDa/FuqJfvcF5DTyiybCSbjlpKPqF/BpPD20ffhpFH+9x8+80Z0EBUNLrIKsWfHVCPHtOmN3F7KRdFCBB+ZGNtx+I57csGz3kQgC2waZKku6YiyD18N4rI4LaEOwq1OldHp84hQ3I3rGL8IWLOGA5sm8SRFWBPKy7pERk/vzEre6AV7P8o/UFe0sus0EYGNM2bl7kRSKtRvpCXJSDcv9wO1sX0wtYMif8TIxvBeLmDh3L93ZVRC7m8f2JoVXHynK6kUYjRgYP7TX+DZxSJDzd2VqNuFfhr3hxFdxgyWNsjk8ZjijFzvT26QStUU3iZLmsHUxWfSsHzHnSsMiS+PgcM5GhXzZFw+iwbJwwHi56kthJkUVn4um5YboBbLYvOPZ4Iut4Nn9r9eGLrWpo6M9G1LkcZGw7qYvXUh4dD9GL+siuM5WrODGLR8JHWSHEy33SiEwVYP9E8UzbmVd0ktCdzg/2LppRli47Ygww1MHlG1VTEmtpVoiWC+i90pqlxWc93UOKURLco04pUz+QUz60jXZskgxjLqPrft9LX2RqtSyESVAYHg9sh04NEmUuiNEe22JKw9MM=
  template:
    metadata:
      creationTimestamp: null
      name: sealed-podsync-api-key
      namespace: downloaders
