---

- name: Etcd certs
  when: inventory_hostname in groups.etcd
  block:
    - name: Create etcd conf dir
      ansible.builtin.file:
        path: /etc/etcd
        state: directory
        mode: '0755'

    - name: Copy certs
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "/etc/etcd/{{ item.dest }}"
        mode: "{{ item.mode }}"
      loop:
        - src: ca.crt
          dest: ca.crt
          mode: '0640'
        # - src: ca.key.aes
        #   dest: ca.key
        #   mode: '0600'
        - src: etcd.crt
          dest: etcd.crt
          mode: '0640'
        - src: etcd.key.aes
          dest: etcd.key
          mode: '0600'

- name: Worker certs
  when: inventory_hostname in groups.workers
  block:
    - name: Create kubelet dir
      ansible.builtin.file:
        path: /var/lib/kubelet
        state: directory
        mode: '0710'

    - name: Copy certs
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
      loop:
        - src: ca.crt
          dest: /var/lib/kubelet/ca.crt
          mode: '0640'
        - src: "{{ inventory_hostname_short }}.crt"
          dest: "/var/lib/kubelet/{{ inventory_hostname_short }}.crt"
          mode: '0640'
        - src: "{{ inventory_hostname_short }}.key.aes"
          dest: "/var/lib/kubelet/{{ inventory_hostname_short }}.key"
          mode: '0600'

- name: Controllers certs
  when: inventory_hostname in groups.controllers
  block:
    - name: Copy certs
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "/root/{{ item.dest }}"
        mode: "{{ item.mode }}"
      loop:
        - src: ca.crt
          dest: ca.crt
          mode: '0640'
        - src: ca.key.aes
          dest: ca.key
          mode: '0600'
        - src: kube-api-server.crt
          dest: kube-api-server.crt
          mode: '0640'
        - src: kube-api-server.key.aes
          dest: kube-api-server.key
          mode: '0600'
        - src: service-accounts.crt
          dest: service-accounts.crt
          mode: '0640'
        - src: service-accounts.key.aes
          dest: service-accounts.key
          mode: '0600'
