annotateK8sNode: true
envoy:
  enabled: false
cgroup:
  automount:
    enabled: false
  hostRoot: /sys/fs/cgroup
devices: eth+
gatewayAPI:
  enabled: true
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
ingressController:
  enabled: true
  loadbalancerMode: dedicated
k8sClientRateLimit:
  burst: 45
  qps: 35
k8sServiceHost: kubernetes
k8sServicePort: 6443
kubeProxyReplacement: true
l2announcements:
  enabled: true
  leaseDuration: 30s
  leaseRenewDeadline: 15s
  leaseRetryPeriod: 5s
