---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sealed-pihole-admin-password
  namespace: external-dns
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgCM9ihPNSfonUJA+vgmcF5iuSFAgMReBYn97N/xt3Zp7Q/T1gaEAryOLJXRfSaTi/uFSiO0BSsLJl7JNSYuZfZZUCrfBKW/FxbROj29Vv/W9hZdo5O64hJMAMUMIA94dtwc5EeYtaQow6FBCk5vJz2xH0dYrLybiXyz1IHWwGcMDoE8yu2qUfXiIQ/FgFqyEWbA9qya/vL3kAsTYpcPZhatFFdVLBd353Xkn0/BoFRMpcTOGYUWTbwVLWMhUSXLlKC06howcXP8bISe8QgIO62QqzsPCcefhgxOpYfslsE53uKFY8JucUfTsCn2lz7yzR1sESywLn8Yb+QJqCsvw9ag6cRcoITkWTM0uolDXFMEkt2DHkNeEEsHf1M5Ye4w2I+jSnkm29JZ62nVrPnqyzpIYmsvKy3DOC/EWArdPZeNu895sj3fys9xV7mFLIlosgipQDLPGa7C/6SZzlN+szT+mELetnX0ZHFMrTTuxTI70mewBL29CZvbbv//jrKkAcRLOou48suWW837435gfrpBvzfL2jbb5cpizVplpilR9QVIf/u9efZplz9IpNDrG0jpIr3sunwT3uD+EHLWEXsmMmZe5/zDGdqjfKtno2Pbz1nZAiORKpF82ytI/Qlv4EWdeVUyN9hlA8jvCVx18kQNTN55ko/2ooZWHjta5S6tuL2/4zqW/6YSNcE13mrWg/+1Ypqr6yccDZg=
  template:
    metadata:
      creationTimestamp: null
      name: sealed-pihole-admin-password
      namespace: external-dns
